# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/Grad/23SP/ENSC894/Proj/dualCore/dualCore.srcs/sources_1/bd/dualCore/ip/dualCore_processing_system7_0_0/dualCore_processing_system7_0_0.xci
# IP: The module: 'dualCore_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Grad/23SP/ENSC894/Proj/dualCore/dualCore.gen/sources_1/bd/dualCore/ip/dualCore_processing_system7_0_0/dualCore_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'dualCore_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: F:/Grad/23SP/ENSC894/Proj/dualCore/dualCore.srcs/sources_1/bd/dualCore/ip/dualCore_processing_system7_0_0/dualCore_processing_system7_0_0.xci
# IP: The module: 'dualCore_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Grad/23SP/ENSC894/Proj/dualCore/dualCore.gen/sources_1/bd/dualCore/ip/dualCore_processing_system7_0_0/dualCore_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'dualCore_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
