# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/ENSC894/Lab/VGA/vga_tutorial_students/zedboard_master.xdc

# XDC: imports/ENSC894/Proj/ip_repo/ringO_loop.xdc

# XDC: imports/constraints/adventures_with_ip.xdc

# Block Designs: bd/dualCore/dualCore.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dualCore || ORIG_REF_NAME==dualCore} -quiet] -quiet

# IP: bd/dualCore/ip/dualCore_processing_system7_0_0/dualCore_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dualCore_processing_system7_0_0 || ORIG_REF_NAME==dualCore_processing_system7_0_0} -quiet] -quiet

# IP: bd/dualCore/ip/dualCore_clk_wiz_0_0/dualCore_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dualCore_clk_wiz_0_0 || ORIG_REF_NAME==dualCore_clk_wiz_0_0} -quiet] -quiet

# IP: bd/dualCore/ip/dualCore_proc_sys_reset_0_0/dualCore_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dualCore_proc_sys_reset_0_0 || ORIG_REF_NAME==dualCore_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/dualCore/ip/dualCore_axi_timer_0_0/dualCore_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dualCore_axi_timer_0_0 || ORIG_REF_NAME==dualCore_axi_timer_0_0} -quiet] -quiet

# IP: bd/dualCore/ip/dualCore_smartconnect_0_0/dualCore_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dualCore_smartconnect_0_0 || ORIG_REF_NAME==dualCore_smartconnect_0_0} -quiet] -quiet

# IP: bd/dualCore/ip/dualCore_vga_controller_0_0/dualCore_vga_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dualCore_vga_controller_0_0 || ORIG_REF_NAME==dualCore_vga_controller_0_0} -quiet] -quiet

# IP: bd/dualCore/ip/dualCore_axi_gpio_0_0/dualCore_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dualCore_axi_gpio_0_0 || ORIG_REF_NAME==dualCore_axi_gpio_0_0} -quiet] -quiet

# IP: bd/dualCore/ip/dualCore_rst_ps7_0_125M_0/dualCore_rst_ps7_0_125M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dualCore_rst_ps7_0_125M_0 || ORIG_REF_NAME==dualCore_rst_ps7_0_125M_0} -quiet] -quiet

# IP: bd/dualCore/ip/dualCore_trng_0_0/dualCore_trng_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dualCore_trng_0_0 || ORIG_REF_NAME==dualCore_trng_0_0} -quiet] -quiet

# IP: bd/dualCore/ip/dualCore_zed_audio_ctrl_0_0/dualCore_zed_audio_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dualCore_zed_audio_ctrl_0_0 || ORIG_REF_NAME==dualCore_zed_audio_ctrl_0_0} -quiet] -quiet

# IP: bd/dualCore/ip/dualCore_axi_gpio_1_1/dualCore_axi_gpio_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dualCore_axi_gpio_1_1 || ORIG_REF_NAME==dualCore_axi_gpio_1_1} -quiet] -quiet

# XDC: f:/Grad/23SP/ENSC894/Proj/dualCore/dualCore.gen/sources_1/bd/dualCore/dualCore_ooc.xdc
